apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterrules.kubevious.io
spec:
  group: kubevious.io
  scope: Cluster
  names:
    plural: clusterrules
    singular: clusterrule
    kind: ClusterRule  
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                target:
                  type: string
                rule:
                  type: string
                values:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  # additionalProperties:
                  #   anyOf:
                  #     - type: string
                  #     - type: integer
                  #     - type: boolean
                  #     - type: object
                disabled:
                  type: boolean
                application:
                  type: object
                  properties:
                    useApplicator:
                      type: boolean
                    onlySelectedNamespaces:
                      type: boolean
                    namespaces: 
                      type: array
                      items:
                        type: object
                        properties:
                          name: 
                            type: string
                          values:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                        required:
                          - name
              required:
                - target
                - rule
          required:
            - spec